# Generated by Django 5.2 on 2025-05-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cash_register',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
